CREATE TABLE Khoa (
  MaKhoa VARCHAR(10) PRIMARY KEY,
  TenKhoa VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE Nganh (
  MaNganh VARCHAR(10) PRIMARY KEY,
  TenNganh VARCHAR(255),
  MaKhoa VARCHAR(10),
  FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Lop (
  MaLop VARCHAR(10) PRIMARY KEY,
  TenLop VARCHAR(255),
  MaNganh VARCHAR(10),
  FOREIGN KEY (MaNganh) REFERENCES Nganh(MaNganh)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE HocKy (
  MaHK VARCHAR(10) PRIMARY KEY,
  TenHK VARCHAR(255),
  ThoiGianBatDau DATETIME,
  ThoiGianKetThuc DATETIME
) ENGINE=InnoDB;

CREATE TABLE SinhVien (
  MSSV VARCHAR(10) PRIMARY KEY,
  Ho VARCHAR(255),
  Ten VARCHAR(255),
  Email VARCHAR(255) UNIQUE,
  Password VARCHAR(255),
  MaLop VARCHAR(10),
  FOREIGN KEY (MaLop) REFERENCES Lop(MaLop)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Admin (
  AdminID VARCHAR(10) PRIMARY KEY,
  Ho VARCHAR(100),
  Ten VARCHAR(100),
  Email VARCHAR(255) UNIQUE,
  Password VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE SuKien (
  MaSK INT AUTO_INCREMENT PRIMARY KEY,
  TenSK VARCHAR(255),
  ThoiGianMoDK DATETIME,
  ThoiGianDongDK DATETIME,
  ThoiGianBatDauSK DATETIME,
  ThoiGianKetThucSK DATETIME,
  GioiHanThamGia INT,
  MaKhoa VARCHAR(10),
  GhiChu TEXT,
  FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE ChoPhepSVKhoaThamGia (
  MaSK INT,
  MaKhoa VARCHAR(10),
  PRIMARY KEY (MaSK, MaKhoa),
  FOREIGN KEY (MaSK) REFERENCES SuKien(MaSK)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE DKSuKien (
  MaLuotDK INT AUTO_INCREMENT PRIMARY KEY,
  MSSV VARCHAR(10),
  MaSK INT,
  ThoiGianDK DATETIME,
  TrangThai ENUM('Đăng ký', 'Hủy đăng ký'),
  FOREIGN KEY (MSSV) REFERENCES SinhVien(MSSV)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (MaSK) REFERENCES SuKien(MaSK)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE MinhChungThamGiaSK (
  IDMinhChung INT AUTO_INCREMENT PRIMARY KEY,
  MSSV VARCHAR(10),
  MaSK INT,
  ThoiGianNop DATETIME,
  FileMinhChung VARCHAR(255),
  TrangThai ENUM('Đã duyệt', 'Chờ duyệt', 'Từ chối'),
  FOREIGN KEY (MSSV) REFERENCES SinhVien(MSSV)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (MaSK) REFERENCES SuKien(MaSK)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE DiemRLSV (
  MSSV VARCHAR(10),
  MaHK VARCHAR(10),
  SoDiem INT,
  PRIMARY KEY (MSSV, MaHK),
  FOREIGN KEY (MSSV) REFERENCES SinhVien(MSSV)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (MaHK) REFERENCES HocKy(MaHK)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE BienDongDRL (
  MaGD INT AUTO_INCREMENT PRIMARY KEY,
  LoaiGD ENUM('Cộng', 'Trừ'),
  MSSV VARCHAR(10),
  NoiDung TEXT,
  ThoiGian DATETIME,
  SoDiem INT,
  FOREIGN KEY (MSSV) REFERENCES SinhVien(MSSV)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE DotDanhGiaRL (
  MaDot INT AUTO_INCREMENT PRIMARY KEY,
  MaHK VARCHAR(10),
  ThoiGianMo DATETIME,
  ThoiGianDong DATETIME,
  FOREIGN KEY (MaHK) REFERENCES HocKy(MaHK)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE PhieuDanhGiaRL (
  MaDot INT,
  MSSV VARCHAR(10),
  ThoiGianNop DATETIME,
  JSON_Data JSON,
  TrangThai ENUM('Đã duyệt', 'Đã điều chỉnh', 'Chờ duyệt', 'Từ chối'),
  PRIMARY KEY (MaDot, MSSV),
  FOREIGN KEY (MaDot) REFERENCES DotDanhGiaRL(MaDot)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (MSSV) REFERENCES SinhVien(MSSV)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;
